timezone: Europe/Berlin
markdown: redcarpet
pygments: true
permalink: /blog/:year/:month/:day/:title

redcarpet:
  extensions: [autolink]

exclude: [README.md, resources, node_modules, Gulpfile.js, package.json, npm-debug.log]